x-common-settings: &common-settings
  volumes:
    - ./cache:/root/.cache:ro
  environment:
    TZ: Asia/Tokyo
  tty: true
  stop_grace_period: 0s
  ipc: host
  security_opt:
    - seccomp:unconfined
  env_file:
    - .env

services:
  proxy:
    image: ghcr.io/berriai/litellm:1.80.15-stable.1
    ports:
      - 4000:4000
    volumes:
      - ./litellm_config.yaml:/app/config.yaml
      - ./message_truncation_callback.py:/app/message_truncation_callback.py
    command: --config /app/config.yaml
    restart: always
  main:
    <<: *common-settings
    # image: kyuz0/amd-strix-halo-toolboxes:vulkan-amdvlk_20260318T132624
    image: kyuz0/amd-strix-halo-toolboxes:rocm-7.2.1_20260413T135331
    ports:
      - "8000:8000"
    devices:
      - "/dev/dri:/dev/dri"
    privileged: true
    restart: always
    # --chat-template-kwargs "{\"enable_thinking\": false}"
    # --reasoning off
    command: >
      /usr/local/bin/llama-server
      --host 0.0.0.0
      --port 8000
      --model /root/.cache/llama.cpp/gemma-4-31B-it-Q4_K_M.gguf
      -ngl 99 --ctx-size 32768 -a gpt-4o-mini --flash-attn on --threads 16 --batch-size 2048 --ubatch-size 1024 --no-mmap
      --jinja
      --cache-reuse 512 --cache-ram -1 --cache-type-k q8_0 --cache-type-v q8_0
