x-common-settings: &common-settings
  image: ghcr.io/ggerganov/llama.cpp:server-cuda
  volumes:
    - ./cache:/root/.cache
  environment:
    TZ: Asia/Tokyo
  tty: true
  stop_grace_period: 0s
  ipc: host

services:
  proxy:
    image: ghcr.io/berriai/litellm:main-latest
    ports:
      - 4000:4000
    volumes:
      - ./litellm_config.yaml:/app/config.yaml
    command: --config /app/config.yaml
    restart: always
  rag:
    <<: *common-settings
    ports:
      - "8001:8000"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['1']
              capabilities: [ gpu ]
    command: >
      --host 0.0.0.0
      --port 8000
      --hf-repo dahara1/Qwen2.5-3B-Instruct-gguf-japanese-imatrix-128K
      --hf-file Qwen2.5-3B-Instruct-Q4_K_M.gguf
      --threads 8
      --n-gpu-layers 99
      --ctx-size 131072
      -a gpt-4o-mini
  vllm:
    <<: *common-settings
    build:
      context: ./vllm
      dockerfile: Dockerfile
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0']
              capabilities: [ gpu ]
    ports:
      - "8002:8000"
    command: --model Qwen/Qwen2-VL-7B-Instruct-AWQ --quantization awq --served-model-name gpt-4o-mini
  main:
    <<: *common-settings
    ports:
      - "8000:8000"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0']
              capabilities: [ gpu ]
      # --hf-repo mmnga/HODACHI-EZO-Common-9B-gemma-2-it-gguf
      # --hf-file HODACHI-EZO-Common-9B-gemma-2-it-Q5_K_M.gguf
      # --hf-repo mmnga/Llama3-ArrowSE-8B-v0.3-gguf
      # --hf-file Llama3-ArrowSE-8B-v0.3-Q5_K_M.gguf
      # --hf-repo dahara1/gemma-2-27b-it-gguf-japanese-imatrix
      # --hf-file gemma-2-27b-it.f16.Q5_k_m.gguf
      # --hf-repo Aratako/calm3-22b-RP-GGUF
      # --hf-file calm3-22b-RP-Q4_K_M.gguf
      # --hf-repo grapevine-AI/c4ai-command-r-08-2024-gguf
      # --hf-file c4ai-command-r-08-2024-Q4_K_M.gguf
      # --hf-repo grapevine-AI/EZO-Qwen2.5-32B-Instruct-GGUF
      # --hf-file EZO-Qwen2.5-32B-Instruct-Q4_K_M.gguf
      # --hf-repo Aratako/calm3-22b-RP-v2-GGUF
      # --hf-file calm3-22b-RP-v2-Q4_K_M.gguf
      # --hf-repo Qwen/Qwen2.5-Coder-7B-Instruct-GGUF
      # --hf-file qwen2.5-coder-7b-instruct-q8_0-00001-of-00003.gguf
      # --ctx-size 32768
      # --hf-repo bartowski/Qwen2.5-Coder-32B-Instruct-GGUF
      # --hf-file Qwen2.5-Coder-32B-Instruct-Q4_K_M.gguf
      # --hf-repo dahara1/Qwen2.5-3B-Instruct-gguf-japanese-imatrix-128K
      # --hf-file Qwen2.5-3B-Instruct-Q8_0-f16.gguf
      # --hf-repo dahara1/Qwen2.5-7B-Instruct-gguf-japanese-imatrix-128K
      # --hf-file Qwen2.5-7B-Instruct-Q4_K_M.gguf
    command: >
      --host 0.0.0.0
      --port 8000
      --hf-repo Aratako/calm3-22b-RP-GGUF
      --hf-file calm3-22b-RP-Q4_K_M.gguf
      --threads 8
      --n-gpu-layers 99
      --ctx-size 4096
      -a gpt-4o-mini
