x-common-settings: &common-settings
  image: ghcr.io/ggml-org/llama.cpp:server-cuda
  volumes:
    - ./cache:/root/.cache:ro
  environment:
    TZ: Asia/Tokyo
  tty: true
  stop_grace_period: 0s
  ipc: host
  security_opt:
    - seccomp:unconfined
  env_file:
    - .env
services:
  main:
    <<: *common-settings
    ports:
      - "8000:8000"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0']
              # device_ids: ['0', '1']
              capabilities: [ gpu ]
    command: >
      --host 0.0.0.0
      --port 8000
      --model /root/.cache/llama.cpp/gemma-4-31B-it-Q4_K_M.gguf
      --threads 8
      --n-gpu-layers 99
      --ctx-size 40000
      -a gpt-4o-mini
      --flash-attn on
      --cache-reuse 512 --cache-ram -1 --cache-type-k q8_0 --cache-type-v q8_0

  # sub:
  #   <<: *common-settings
  #   ports:
  #     - "8001:8000"
  #   deploy:
  #     resources:
  #       reservations:
  #         devices:
  #           - driver: nvidia
  #             device_ids: ['1']
  #             capabilities: [ gpu ]
  #   command: >
  #     --host 0.0.0.0
  #     --port 8000
  #     --hf-repo unsloth/Qwen3-30B-A3B-Instruct-2507-GGUF
  #     --hf-file Qwen3-30B-A3B-Instruct-2507-Q4_K_M.gguf
  #     --threads 4
  #     --n-gpu-layers 30
  #     --ctx-size 4096
  #     -a gpt-4o-mini
  #     --jinja --temp 0.7 --min-p 0.0 --top-p 0.80 --top-k 20 --presence-penalty 1.0 

  # cpu:
  #   <<: *common-settings
  #   image: ghcr.io/ggml-org/llama.cpp:server
  #   ports:
  #     - "8002:8000"
  #   command: >
  #     --host 0.0.0.0
  #     --port 8000
  #     --hf-repo unsloth/Qwen3-30B-A3B-Instruct-2507-GGUF
  #     --hf-file Qwen3-30B-A3B-Instruct-2507-Q8_0.gguf
  #     --threads 8
  #     --ctx-size 4096
  #     -a gpt-4o-mini

  # benchmark:
  #   <<: *common-settings
  #   image: ghcr.io/ggml-org/llama.cpp:full
  #   entrypoint: '/app/llama-bench'
  #   command: >
  #     -m /root/.cache/llama.cpp/unsloth_Qwen3-30B-A3B-Instruct-2507-GGUF_Qwen3-30B-A3B-Instruct-2507-Q8_0.gguf
  #     -r 2
  #     --n-prompt 512
  #     --n-gen 128
  #     --batch-size 128,256,512,1024,2048
  #     --threads 8
  #     --flash-attn 1
