litellm_settings:
  # ファイル名.インスタンス名 で指定
  callbacks: ["message_truncation_callback.message_truncation_handler"]

model_list:
  - model_name: main
    litellm_params:
      model: openai/gpt-4o-mini
      api_base: http://main:8000
      api_key: sk-dummy

  - model_name: deep01
    litellm_params:
      model: openai/gpt-4o-mini
      api_base: http://192.168.16.20:8000
      api_key: sk-dummy

  - model_name: deep01-reasoning-off
    litellm_params:
      model: openai/gpt-4o-mini
      api_base: http://192.168.16.20:8000
      api_key: sk-dummy
      extra_body:
        chat_template_kwargs:
          enable_thinking: false

  # - model_name: cpu
  #   litellm_params:
  #     model: openai/gpt-4o-mini
  #     api_base: http://cpu:8000
  #     api_key: sk-dummy
