version = 1

[*]
n-gpu-layers = 99
load-on-startup = false

[unsloth/Qwen3-235B-A22B-Instruct-2507-GGUF:UD-Q3_K_XL]
hf = unsloth/Qwen3-235B-A22B-Instruct-2507-GGUF:UD-Q3_K_XL
ctx-size = 32768
threads = 16

flash-attn = true

batch-size = 2048
ubatch-size = 1024

no-mmap = true
cache-reuse = 512
cache-ram = -1
cache-type-k = q8_0
cache-type-v = q8_0

jinja = true

load-on-startup = true

[unsloth/Qwen3-4B-Instruct-2507-GGUF:Q8_0]
hf = unsloth/Qwen3-4B-Instruct-2507-GGUF:Q8_0
ctx-size = 32768
threads = 16

flash-attn = true

jinja = true

load-on-startup = false

; temperature = 0.6
min-p = 0.0
top-p = 0.95
top-k = 20
presence-penalty = 1.0

